dist: trusty
sudo: required

language: go
go:
  - 1.12.7

services:
  - docker

jobs:
  include:
    - stage: test
      script: make coverage

stages:
  - name: test

after_success:
  - bash <(curl -s https://codecov.io/bash)
